source = ./outputs.conf

$laptop_display_config = $laptop_display, 2560x1600@240Hz, 0x0, 1.25
monitor = $laptop_display_config
monitor = desc:$ultrawide_display, 7680x2160@120Hz, auto-up, 1.25
monitor = , preferred, auto-up, 1

bindl=,switch:off:Lid Switch,exec,$HOME/.config/hypr/scripts/clamshell-mode.sh --reason lid-open --settle-seconds 1 --retry-interval 0.25
bindl=,switch:on:Lid Switch,exec,$HOME/.config/hypr/scripts/clamshell-mode.sh --reason lid-close --settle-seconds 3 --retry-interval 0.25
