source = ./conf-enabled/*.conf

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc { 
    # ban hyprchan
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule (matcher syntax)
# windowrule = match:class ^(kitty)$, match:title ^(kitty)$, float on

windowrule = match:class .*, suppress_event maximize # You'll probably like this.
